### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lHabetha** [harrynull/WoxDictionary#21]
[2022-12-18.txt](https://github.com/harrynull/WoxDictionary/files/10254343/2022-12-18.txt)

Flow Launcher version: 1.10.1
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 12/18/2022 18:29:05
Exception:
Dictionary Exception: 
Websites: https://github.com/harrynull/WoxDictionary
Author: Harry Yu
Version: 2.2.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
 ---> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at Dictionary.ECDict.QueryAsync(String word, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\ECDict.cs:line 36
   at Dictionary.Main.FirstLevelQueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 158
   at Dictionary.Main.QueryAsync(Query query, CancellationToken token) in D:\a\Flow.Launcher.Dictionary\Flow.Launcher.Dictionary\src\Dictionary.cs:line 343
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 740
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pzzzling** [comment]
插件最新版本到2.3.2了，试着更新一下？
我原来也是2.2.3，更新之后好像就不报错了
